apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample3
spec:
  destination:
    namespace: kamransaeed
    server: https://kubernetes.default.svc
  source:
    path: ./
    repoURL: https://github.com/kamran90-web/k8s-declarative.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
