apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: circle-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kamransaeed
    server: https://kubernetes.default.svc
  source:
    path: ./declarative/manifests/cirle
    repoURL: https://github.com/kamran90-web/k8s-declarative.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

